import { useEffect, useState } from "react";
import { Activity, ArrowRight, CalendarDays, Clock3, FileText, Plus, Users } from "lucide-react";
import { getDashboard } from "../../api/dashboard";
import { PageHeading } from "../../components/PageHeading";
import type { TranslationKey } from "../../i18n";
import type { AppView } from "../../app/routes";
import type { Role } from "../workspace/navigation";

type Translator = (key: TranslationKey) => string;
type Props = { onNavigate: (view: AppView) => void; doctorName: string; t: Translator; role: Role; department: string; project: string };

export function Dashboard({ onNavigate, doctorName, t, role, department, project }: Props) {
  const [data, setData] = useState<Awaited<ReturnType<typeof getDashboard>> | null>(null);
  useEffect(() => { getDashboard().then(setData).catch(() => setData(null)); }, []);
  const patientCount = data?.patient_count ?? 18;
  const appointmentCount = data?.upcoming_appointments?.length ?? 4;
  return <><PageHeading eyebrow={t("todayOverview")} title={`${t("morning")}, ${doctorName}`} detail={t("todayOverview")} action={<button type="button" className="primary-btn" onClick={() => onNavigate("appointments")}><Plus size={16} /> {t("newAppointment")}</button>} /><div className="scope-strip"><span>Department: {department}</span><span>Project: {project}</span></div><section className="stat-grid"><div className="stat-card"><div className="stat-icon blue"><Users /></div><span className="stat-label">{t("activePatients")}</span><strong className="stat-value">{patientCount}</strong><span className="stat-delta blue">{t("syntheticData")}</span></div><div className="stat-card"><div className="stat-icon green"><CalendarDays /></div><span className="stat-label">{t("appointments")}</span><strong className="stat-value">{appointmentCount}</strong><span className="stat-delta green">{t("today")}</span></div><div className="stat-card"><div className="stat-icon orange"><Clock3 /></div><span className="stat-label">{t("followUps")}</span><strong className="stat-value">{data?.followups?.length ?? 7}</strong><span className="stat-delta orange">{t("needsAttention")}</span></div><div className="stat-card"><div className="stat-icon rose"><Activity /></div><span className="stat-label">{t("aiReviewRate")}</span><strong className="stat-value">{role === "doctor" ? "100%" : "92%"}</strong><span className="stat-delta rose">{t("reviewAi")}</span></div></section><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>{t("upcomingAppointments")}</h2><p>{t("scheduleDetail")}</p></div><button type="button" className="text-btn" onClick={() => onNavigate("appointments")}>{t("viewAll")} <ArrowRight size={14} /></button></div>{(data?.upcoming_appointments ?? []).slice(0, 4).map((appointment) => <div className="record-item" key={appointment.id}><div className="record-date"><CalendarDays size={16} /></div><div><strong>{new Date(appointment.starts_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</strong><p>{appointment.reason}</p></div><span className="status confirmed">{appointment.status}</span></div>)}{!data?.upcoming_appointments?.length && <div className="empty-state">{t("noAppointments")}</div>}</section><section className="panel"><div className="panel-heading"><div><h2>{t("clinicalWorkspace")}</h2><p>{t("reviewAi")}</p></div></div><div className="record-item"><div className="record-date"><FileText size={16} /></div><div><strong>{t("notes")}</strong><p>{t("notesDetail")}</p></div><button type="button" className="text-btn" onClick={() => onNavigate("notes")}>{t("open")}</button></div><div className="record-item"><div className="record-date"><Users size={16} /></div><div><strong>{t("patients")}</strong><p>{t("searchManage")}</p></div><button type="button" className="text-btn" onClick={() => onNavigate("patients")}>{t("open")}</button></div></section></div></>;
}
